name: CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Checking PHP syntax error
      uses: overtrue/phplint@7.3
      with:
        path: .
        options: --exclude=*.log
